### ISSUE TITLE
Keeping track of active functions, routines etc.

### ISSUE THREAD

**Issue by kflak** [dathinaios/CuePlayer#11]
Hi there, I am thinking of ways to keep track of all the unholy stuff I have launched while running through a cue list, and also to be able to step through a cuelist quickly without having to clean up manually or calling .value on a bunch of `nil` functions that have not yet been initialized. It would also be handy to be able to hop back and forth between different cues and know that the house-keeping would be taken care of for me.

To do this I am considering writing a Cue class that would function as a wrapper for the cue-function. Each cue would also take an optional cleanup-function that could be triggered at will when skipping forward in the cuelist (which is a very common scenario for me when soundchecking for a show)... The cue would also do all the nil checks, to make sure a nil.value doesn't break the cuelist.

It seems some of this functionality is already implemented by the attachmentList in the Cues class, but it's not quite clear to me how this works. Obviously I'd prefer not to reinvent too many wheels, so if there is already a way of accomplishing what I'm looking for with the existing structure, I'd be very happy to learn more about this!

**Comment by dathinaios** [comment]
Hello 🙂

There is already a mechanism to register a function that is evaluated right before every cue. This is the `hook` method of `CuePlayer`:

```ruby
.hook = value

// Register a function to be avaluated right before 
// triggering a new cue. The function is passed in 
// the cuePlayer as an argument.

b = CuePlayer.new;

b.hook = {arg cueplayer; cueplayer.current.postln; }

```

You should be able to use it for any kind of cleanup necessary. The function accesses the `CuePlayer` instance as shown above so you don't have to use any kind of external variable or suchlike. Possibly a `case` with different actions for different cues and conditions but it depends on your setup. 

Let me know if you still have trouble achieving what you need.

**Comment by sarcman** [comment]
γαμάς

**Comment by kflak** [comment]
The `hook` method is very interesting, thanks a lot for the pointer! I would have to look into it a bit more in detail, but I suspect this will lead to much chaos in my setups, as I would have to keep the cleanup functions in one place and the cues themselves in another. My dream scenario is to be able to do something like:
```
b = CuePlayer.new;
b.add(cueFunc, cleanupFunc);
```
and that would be that...

**Comment by dathinaios** [comment]
But when is the `cleanupFunc` going to be evaluated? It seems to me that if it is to be evaluated after a specific time you can use the timeline option available in the `add` or `put` argument. If on the other hand it is always to be defined anew for every cue then you should be able to update the `hook` inside the function of your cue and problem solved. Something like:

```ruby
a = CuePlayer.new; // Create a new CuePlayer instance

a.put(1, { "do something".postln });
a.put(2, { 
  "this is the 2nd cue".postln;
   a.hook{arg cueplayers; "cleanup something".postln;}
});
a.put(3, { 
  "& this is the 3d cue".postln;
  // the previous hook has already been evaluated so now
  // we can define a new one
  a.hook = {arg cueplayer; "cleanup something related to 3".postln;}
});
```

So, the above doesn't look that different to defining a cleanup argument. Maybe if I understand the specific things you need to cleanup I will get what case is not covered by the current functionality and then we can convert this to a feature request 🙂

Let me know what you think!

**Comment by kflak** [comment]
Thanks a lot for taking the time to think through this! I'm still trying to figure out how exactly I would want to use this. Updating the `hook` in the way you propose solves one problem elegantly: it collects all the housekeeping within the same cue, which means I don't have to call it from the next cue -> I can skip back and forth between cues without worrying too much about what should be freed up or not. 

I love the timeline feature, and one of the main reasons for opening this issue is to find a way to fast-forward a timeline sequence within a cue. For example, this is  a very typical (abbreviated) cue I use: 
```
    ~cuelist = CuePlayer.new(); 
    ~cuelist.add(timeline: 
        [
            0, {this.executeFile(~sketchdir+/+"klliMicBreath.scd")},
            360, {
                ~klliMicBreath !? {~klliMicBreath[\fx].free};
                ~klliMicBreath !? {~klliMicBreath[\water].stop};
                ~klliMicBreath !? {~klliMicBreath[\osc].clear};
                ~klliMicBreath !? {~klliMicBreath[\amp].free};
                ~klliMicBreath !? {~klliMicBreath[\timeline].stop}, 
                this.executeFile(~sketchdir+/+"breathulator.scd");
                ~breathulatorFx.play;
                ~breathulator[4..7].do(_.play);
            }, 
            420, {
                "trumpetulator".postln,
                this.executeFile(~sketchdir+/+"trumpetulator.scd"),
                ~trumpetulatorFx.level = -6.dbamp,
                ~trumpetulatorFx.fadeInTime = 240,
                ~trumpetulatorFx.fadeOutTime = 120,
                ~trumpetulatorFx.play,
                ~trumpetulator[4..5].do(_.play);
            },
            450, {~breathulator !? {~breathulator[4..5].do(_.free)}}, 
            480, {~trumpetulator !? {~trumpetulator[6..7].do(_.play)}}, 
        ],
        function: {
            ~cuelist.hook = {|cl| 
                ~klliMicBreath !? {~klliMicBreath[\fx].free};
                ~breathulatorFx !? {~breathulatorFx.free}; 
                ~breathulator !? {~breathulator.do(_.free)}; 
            }
        }
    ); 
```
My main issue, as you can probably tell from all those `!?` statements, is that I need to define some global variables in external files, and calling `free` on these when not yet initialized breaks the current function evaluation. So my motivation right now is to find a way of squirreling away those nil checks in a class somewhere, so I don't have to think about including them anymore. It gets quite cluttered when the cuelist grows beyond 400 sloc... Obviously, this is probably because of some overall design flaw on my part ;-) 

The other motivation is to be able to define a kind of snapshot of the timeline at every stage, spending for example 10 seconds on each instance of it to be able to get into a theater and quickly run through the cues without having to wait the full 7-8-9 minutes for it to play out. I am mainly using this for dance performances where I am dancing in it myself and don't have the option to break the cue down into smaller chunks...

**Comment by dathinaios** [comment]
First of all, independently of the specific issues I agree that `TimeLine` should have a method for playing from a specific time instead of always at the start. I had this issue myself and had implemented this functionality but that was before `CuePlayer` and I haven't added the feature yet. I've noted this for a future update as I agree it is important 👍 

Even with the above functionality implemented though the playback will still depend on the nature of the function scheduled. I remember even when I had this working I still had to wait through long sections when the processes depended on previous evaluations. It is an interesting problem though, I will try to rethink possible ways to get around these limitation 🤔

Now, to the specifics of your setup.  I am inevitably making assumptions about what your design is so this might not be relevant. If that is the case let me know. Extensive use of `!?` does indicate to me that this is something you can solve on your design before `CuePlayer` comes into the picture. It seem you are using `JitLib` proxies through its live coding style (`p = ProxySpace.push(s);` etc.). I personally tend to use `NodeProxies` directly and I am wondering if just changing this in your design would solve the issue. For example:

``` c
a = NodeProxy.new;
a.play;
a.source = {Impulse.ar(30, mul: 0.2)};
a.stop;
```

``` c
// Non of the following throws an error
// even if the NodeProxy is not currently active
// as the var 'a' still contains it.
a.stop;
a.clear;
a.free;
```

**Comment by kflak** [comment]
Yeah, the age-old problem of dependencies on former processes... These days I mostly do stuff with MiniBee movement sensors to trigger sound and run them through my own  [FxChain](https://gitlab.com/kflak/supercollider-quarks/-/blob/patternFxChain/KFUGen/FxChain.sc) class. The triggering is done with [these](https://gitlab.com/kflak/supercollider-quarks/-/tree/patternFxChain/MiniBeeUtils) classes, none of which use `ProxySpace` (at least not yet)... My projects tend to get quite big, which is why I need to keep them organized in different files. However, I think the `TimeLine` and `hook` combination is taking me a long way in the right direction, and I might have to live with the nil checks for now.

I am wondering if there is an easy way to replace the time values of a `TimeLine` quickly and temporarily, in order to get the kind of fast-forward behavior I would like to see, something that may not even be a part of the class.

On a related note: how do you access the timeline of a cue? I couldn`t quite figure it out by looking at the code... I would like to be able to stop this as a part of the cleanup hooks...

**Comment by dathinaios** [comment]
Ah I see. As expected from a SC user your workflow is too specific for me to be able to make very relevant comments 😬 Still, I am fairly confident that having to use `??` or `!?` extensively indicates something to be resolved inside your classes / general workflow. But that depends on what exactly is returned and stored in these global variables etc. so I can't say much more...

The timelines are stored in a Dictionary that you can access from your `CuePlayer` instance using the cue number as the key:

```c
~cuelist.timelineRegister; // the dictionary
// to access the `TimeLine` of a specific cue
~cuelist.timelineRegister[\3]; // timeline of cue 3
```

You can then use all the methods of `TimeLine`. You can `stop` it and then recreate it but not sure how to achieve the fast forward behaviour at the moment. Will need to give it some thought. Hopefully that gives you enough to hack away on your issues 😄

(Edit: I've [added](https://github.com/dathinaios/CuePlayer/commit/ede0bb327aff65c2027d02521ae31f245b4da2dc) the `timelineRegister` info to the help file 👍)

**Comment by kflak** [comment]
Great, thanks a lot for your thoughts! I'll have to think long and hard about how I initialize the variables, but you have pointed me in some very interesting directions...

**Comment by kflak** [comment]
For simply stepping through the functions of a timeline every 10 seconds, one could probably do something like this:
```
t = 0;
~testTimeline = Timeline.new;
~cuelist.timelineRegister[\1].functionList.pairsDo{|i, j| ~testTimeline.add(t, j); t = t + 10};
~testTimeline.play;
````

EDIT: made a sloppy little mistake in the scheduling...

**Comment by kflak** [comment]
Hi there, 

I am not sure if this warrants reopening the issue, or if this would be better off in a separate issue, but I'm ending up in a situation now where I have 30 minute long timelines with no way of going to specific points in time. I was wondering if it would be possible to implement this behaviour through setting the `clock`, something in line with 
```supercollider
~cuelist.clock.beats = 290;
``` 
to be able to go directly to time 290, but this doesn't work, unfortunately. The use case is to be able to start the show from a specific point in time and let it run in real time after that.

**Comment by dathinaios** [comment]
I have created a new issue/feature request. I agree that this is very important!
