### ISSUE TITLE
Provide mechanism to start a TimeLine from a specific time offset

### ISSUE THREAD

**Issue by dathinaios** [dathinaios/CuePlayer#13]
> ... I'm ending up in a situation now where I have 30 minute long timelines with no way of going to specific points in time. I was wondering if it would be possible to implement this behaviour through setting the `clock`, something in line with 
> ```supercollider
> ~cuelist.clock.beats = 290;
> ``` 
> to be able to go directly to time 290, but this doesn't work, unfortunately. The use case is to be able to start the show from a specific point in time and let it run in real time after that.

_Originally posted by @kflak in https://github.com/dathinaios/CuePlayer/issues/11#issuecomment-670054806_

**Comment by kflak** [comment]
Yes!!!

**Comment by dathinaios** [comment]
@kflak I finally had a go at this! Would you mind testing it and give some feedback?

In theory all you need to do is add an offset argument in the timeline options. For example:

```javascript
(
c = TempoClock(5);
t = Timeline.new(clock: c, options:(mode: \beats, quant: 1, offset: 2));
t.add(0.5, {"test 1".postln});
t.add(1, {"test 2".postln});
t.add(2, {"test 3".postln});
t.add(4.3, {"test 4".postln});
t.add(9, {"test 5".postln});
);

t.play;
t.plot;
```
When using `CuePlayer` just put the offset argument in the `timelineOptions`.

Here is the `Timeline.sc` file. Just replace the current one and give it a try:

[Timeline.sc.zip](https://github.com/dathinaios/CuePlayer/files/5506858/Timeline.sc.zip)

**Comment by kflak** [comment]
Awesome! Will give it a try when I have a bit more time, hopefully this week!

**Comment by iani** [comment]
Very interesting. Will also check this.

Iannis

**Comment by dathinaios** [comment]
Completely forgot about this one 😄

@kflak , @iani  Any of you had the chance to test it?

**Comment by kflak** [comment]
Hi there,

Sorry, didn’t have a chance to test it yet! Time just flies by, even in these COVID times... hopefully I’ll have a chance to check it out next week.

**Comment by dathinaios** [comment]
I will have to assume this is working fine 😉

**Comment by kflak** [comment]
Yes, I suppose so ;-) never got around to testing it, sorry! But it's very, very good to know that the feature is there...

--
Roosna & Flak - Contemporary Dance & Music
Web: roosnaflak.com
Code: {github,gitlab}.com/kflak
Mastodon: @***@***.***
