### ISSUE TITLE
server's volume-fader

### ISSUE THREAD

**Issue by sarcman** [dathinaios/CuePlayer#15]
On CuePlayer-GUI, the server's volume-fader does not respond to s.volume

**Comment by dathinaios** [comment]
This would have to be set in the CuePlayer GUI and not directly on the server. I have added a method `setServerVolume` and it will be available in the next update.  Usage:

```supercollider
(
c = CuePlayer.new; 
c.put(1, { "one".postln }); 
c.put(2, { "two".postln; ().play; }); 
c.put(3, { "three".postln }); 
c.gui;
);
c.guiInstance.setServerVolume(0.5);
```
