### ISSUE TITLE
Bug: Making a new cueplayer adds a new cmd period with synths

### ISSUE THREAD

**Issue by madskjeldgaard** [dathinaios/CuePlayer#17]
Hi

I just noticed that if you make a new cueplayer instance, another CmdPeriod callback will be registered, resulting in many copies of the input and output synths being played eventually if you keep reevaluating. 

Perhaps a flag should be set once the cmd period is added for cueplayer to make sure it isn't added more than 1 time ? 

Thanks ! <3

**Comment by dathinaios** [comment]
Thanks, that certainly should not be per instance. I haven't really tested `CuePlayer` when using multiple instances so if you find other issues around this let me know. At some point I was considering making it a singleton so another instance could not even be created. If you have the time let me know of the use case for multiple instances.

**Comment by madskjeldgaard** [comment]
This fixes the immediate problem at least for me: https://github.com/dathinaios/CuePlayer/pull/20
