### ISSUE TITLE
newest updates not in master branch 

### ISSUE THREAD

**Issue by tatecarson** [dathinaios/CuePlayer#6]
Hi, i'm not the best at git so maybe i'm missing something but the updates you mentioned on the SC board are not here: 

https://github.com/dathinaios/CuePlayer/blob/master/Cues.sc

but I did see them in the commit history: 

https://github.com/dathinaios/CuePlayer/commit/cdbedd0975ee40473f527b1de70bbc44bf202127

Not sure what's wrong. 

Also..random question. If I called git clone https://github.com/dathinaios/CuePlayer.git should doing that again update to the newest version? I tried and it put another cueplayer folder inside the one that already existed instead of only updating the changed parts like I expected.

**Comment by dathinaios** [comment]
Hi there,

You don't need to manage CuePlayer through git. The easiest way to install it and update it is to run `Quarks.gui` from SuperCollider and use the graphic interface. If you want to download the new version manually you can do it from the [release page](https://github.com/dathinaios/CuePlayer/releases).

If you stil want to do it using git though you do `git clone` when you first get it and then you can use `git pull` to pull the latest changes when you want to.

**Comment by tatecarson** [comment]
Hi, sorry. I did try that but I don't see it in the list. Also the most recent updates still don't look like their on the master.

**Comment by dathinaios** [comment]
Did you do `Check for Updates` in the Quarks GUI? It seems to find it fine here.. `CuePlayer` appears on the list with all the versions available for download.

The latest version has nothing to do with the `Cues.sc` files. For details on the new features check the `CueInfo` and `CuePlayer` help files as well as the tutorial.

If you can not get it to work from there you can download the latest version manually from the [release page](https://github.com/dathinaios/CuePlayer/releases).

But I am not clear what you are trying to do? Are you using the quarks system or trying to do a `git pull`? I recommend using the Quarks system. Also what system are you on (Mac, Linux, Window) and which version of SC.

**Comment by dathinaios** [comment]
Also check my answer [here](http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/New-Quark-CuePlayer-td7628875.html) in case it is relevant :)

**Comment by tatecarson** [comment]
I'm on OSX 10.11.6 and SC 3.8.0 

Shouldn't it be listed here? 

![screen shot 2016-12-15 at 1 31 04 pm](https://cloud.githubusercontent.com/assets/12865394/21242780/c87eb25e-c2ca-11e6-89f6-4aac5b22c4a6.png)

Quarks.install("CuePlayer") also throws a quark not found error.

**Comment by dathinaios** [comment]
Yes, it should be there. Are you sure you have clicked 'check for updates'? Also make sure it is not at the top of the list. 

But if you say that `Quarks.install("CuePlayer")` did not work it seems to me that you have a problem with your quarks and not with `CuePlayer`. It is working fine for me and for kflak that asked me on the sc-users list.

When I do `check for updates` at the Quarks GUI that is what I see in the post window:

```
Fetching https://github.com/supercollider-quarks/quarks.git
From https://github.com/supercollider-quarks/quarks
 * branch            master     -> FETCH_HEAD
```

If it does not update the quarks list correctly you might have to ask at the sc-users list.

EDIT: If you keep having trouble dont forget you can download it manually from the release page I linked above. [Check the README for where to place the files.](https://github.com/dathinaios/CuePlayer)

**Comment by tatecarson** [comment]
Check for updates worked. 

I was getting it manually before but for some reason it wasn't the most recent. Using the quarks interface seems better. Wasn't this not a quark when it was first released? I think that's why I did it that way to begin with. 

thanks.

**Comment by dathinaios** [comment]
No problem. 

Yes, it was always a Quark. And it is definitely better to manage it through the Quarks GUI.

Glad its working for you!

:)
